### ISSUE TITLE
Make Task List

### ISSUE THREAD

**Issue by igmsebastian-commude** [commude/penpen#35]
- [x] Apply Raw Html Page to Laravel Blades
- [x] Make WEB -- /tasks
- [x] Prepare functionality for Favorite / Unfavorite
    - Make PUT API -- /api/tasks/{id}/
